image: php:7.3-fpm-alpine

cache:
  paths:
    - vendor/

#before_script:
#  - apt-get update -qq && apt-get install -y -qq zip

deploy:
  stage: deploy
  environment: Staging
  only:
    - development
  script:
    - rm ./composer.lock
    - composer install
    - ./vendor/bin/phpstan analyse
