image: php:7.3

cache:
  paths:
    - vendor/


before_script:
  - bash ci/docker_install.sh > /dev/null

deploy:
  stage: deploy
  environment: Staging
  only:
    - development
  script:
    - rm ./composer.lock
    - composer install
    - ./vendor/bin/phpstan analyse
