image: php:7.3

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq > /dev/null
  - apt-get install git zip wget -yqq > /dev/null
  - docker-php-ext-install pdo_mysql > /dev/null
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"

deploy:
  stage: deploy
  environment: Staging
  only:
    - development
  script:
    - rm ./composer.lock
    - php composer.phar install
    - ./vendor/bin/phpstan analyse
