image: debian

stages:
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass

deploy_stage:
  stage: deploy
  only:
    - development
  script:
    - sshpass -V
    - export SSHPASS=$SSH_PASSWORD
    - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$SSH_HOST 'cd /var/www/datepoll-backend;'
