image: php:7.4-fpm

cache:
  paths:
    - vendor/

before_script:
  - apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-mysql-client \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libmagickwand-dev \
    libzip-dev \
    libonig-dev \
    libc-client-dev \
    libkrb5-dev \
    locales \
    zip \
    unzip \
    git \
    supervisor \
    jpegoptim optipng pngquant gifsicle
  - docker-php-ext-install pdo_mysql pcntl opcache > /dev/null
  - docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-install imap > /dev/null
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"

deploy:
  stage: deploy
  environment: Staging
  only:
    - development
  script:
    - rm ./composer.lock
    - php composer.phar install -n -v
    - ./vendor/bin/phpstan analyse --memory-limit=1G ||  echo 0;
